### ISSUE TITLE
Control Vehicle using pycarmaker

### ISSUE THREAD

**Issue by nirmal-jose** [gmnvh/pycarmaker#12]
Hello pycarmaker team,

Thank you for this fantastic package 🤩. I'm new to CarMaker and was exploring this package. I was able to read parameters from the CarMaker simulation. I would like to know how or whether it is possible to control vehicle acceleration and steering angle with pycarmaker? It would be great if you could have an example for the same.

Thank you for your time.

Regards,
Nirmal Jose

**Comment by gmnvh** [comment]
Hey Nirmal, sorry for the late reply.

Did you try example 4 in the example folder? Try that and see if it is enough for your needs.

Gus

**Comment by nirmal-jose** [comment]
Hi @gmnvh , 

Thanks for the reply. Yes, I could do this by referring to example 4 and some material online. 

Regards,
Nirmal Jose
