### ISSUE TITLE
Co-simulation between SUMO and Carmaker 

### ISSUE THREAD

**Issue by buntyk48** [gmnvh/pycarmaker#15]
Hello All,

I want to retrieve the vehicle data (Vehicle Position) using the Python module pycarmaker.

I also want to further set the co-simulation between SUMO and CarMaker using Python. But I have no idea whether pycarmaker is cable of doing that.

Thanks,
Paras

**Comment by strausswang** [comment]
Do you get any solutions for this problem?

**Comment by buntyk48** [comment]
No, I didn’t find any solution and I dropped the idea of working with
Carmaker. No I am working with Carla.
