### ISSUE TITLE
How to install pycarmaker on linux Ubuntu 18.04?

### ISSUE THREAD

**Issue by MEKH1** [gmnvh/pycarmaker#7]

**Comment by gmnvh** [comment]
I think the easiest way is just to download the code to your project folder. No installations needed. But I actually never tested this script on Linux. I am planning to do it but it will happen just a couple months from now.

**Comment by MEKH1** [comment]
did you use CMROSIF to extract the data from carmaker ?

**Comment by gokhanalcan** [comment]
Just download the pycarmaker repo and install it.
Run the carmaker as `CM -cmdport 16660`
I tested on Ubuntu 18.04, it works. No need for CMROSIF.

**Comment by gmnvh** [comment]
Thanks gokhanalcan for using and testing this.
